server:
  port: 8888
spring:
  # 数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tinder2?serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池最大连接数
      maximumPoolSize: 64
      # 最小空闲连接数量
      minimumIdle: 16
      # 连接超时时间(毫秒)，默认值30秒.
      connectionTimeout: 30000
      # 空闲连接超时时间，默认值600000(10分钟),只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      # 如果大于等于 max-lifetime 且 max-lifetime>0，则会被重置为0.
      idleTimeout: 600000
      # 连接最大存活时间，默认值30分钟。设置应该比mysql设置的超时时间短
      maxLifetime: 3000000
  # 初始化
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      encoding: UTF-8
  h2:
    console:
      enabled: true
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 29
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 3s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1s
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8
  cache:
    multi:
      #是否存储空值，默认true,防止缓存穿透
      cache-null-values: true
      # 一级缓存（内存）
      caffeine:
        # 写入后过期时间，5分钟
        expire-after-write: 5m
      redis:
        # 过期时间，10分钟
        default-expiration: 10m
  # 国际化
  messages:
    basename: i18n/common,i18n/example

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.data.redis: DEBUG

############## 安全认证 ##############
soul:
  security:
    # 注解式鉴权
    annotation:
      # 开启注解式鉴权
      enabled: true
    # URL 式鉴权
    filter:
      # 忽略鉴权
      exclude-path-patterns:
        - /api/v1/token/**
        - /free/tinder/**
      # 鉴权
      path-patterns:
        - path-pattern: /tinder/**
          access: authentication()
    # token 配置
    token:
      type: jwt
      # token 解析参数名称：query > header > cookie
      name: soultoken
      # JWT 配置
      jwt:
        # 密钥
        key: soul12345678soul9soul87654321soul
        # 算法
        algorithm: HS256
        # token 过期时间（秒）
        expires-in: 3600
liquibase:
  url: ${spring.datasource.url}
  driver: ${spring.datasource.driverClassName}
  password: ${spring.datasource.password}
  username: ${spring.datasource.username}
  enabled: true
  change-log: classpath:liquibase/master.xml
netty:
  serverPort: 8100
meta:
  etcdUrl: http://192.168.3.16:2379
  etcdKey: /juntai_test/node
  simulationUrlHead: http://192.168.3.10:8199
  # ZMQ
zmq:
  subscribe:
    enabled: true
    address: tcp://192.168.3.10:35580
    topic:


